### PR TITLE
Properties of type did not output useful information

### PR DESCRIPTION
**Pull request by dennisroche**

### CODE REVIEW

**Comment by andrewabest** [comment]
Howdy Dennis - I feel like this one introduces a couple of behaviors that are beyond the 'useful information' premise of the PR -

- It should only apply to writable properties
- It should apply down the types inheritance chain

I think the inheritance behavior should be optional, and so a bool with a default value of `false` should be introduced into the constructor to allow for this - preserving the original behavior while enabling the new behavior.

I don't like the constraint to only writable properties here though, can you elaborate on the need for that?

**Comment by dennisroche** [comment]
> It should apply down the types inheritance chain

Agree, this should also be configurable. 

> It should only apply to writable properties

The need for it is that on your domain you may have a computed property, that may not want to apply the attribute requirement on. e.g. `FullAddress` computed field on an `Address` value object. Using the convention to ensure that we have `[MaxLength]` on all `string` fields so that they can be indexed. 

Baking this into the specification is incorrect. It should also be configurable.

**Comment by andrewabest** [comment]
That makes sense - happy for them both to be boolean values with defaults to the previous behavior. I don't see the need for a more complex type for the 'writablePropertiesOnly' arg, unless you can think of one. 

If you could update the static factory class too and have the defaults through the chain that would be good.

**Comment by dennisroche** [comment]
The inheritance chain for property attributes doesn't make sense when I started to write a test to prove it worked.

**Pull request merged**
