### PR TITLE
Adds UsingStatementsMustNotBeNestedAnalyzer

### PR DESCRIPTION
**Pull request by brendankowitz**

### CODE REVIEW

**Comment by andrewabest** [comment]
Ooo does this mean Conventional is being used somewhere in MS-land @brendankowitz? :) will have a pore over this in the next few days :+1:

**Comment by brendankowitz** [comment]
There is potential, I'm just playing around with the Roslyn analysers at the moment, really like the idea. Need to way to have some stronger enforcement of a few rules instead of manually calling stuff out in code reviews all the time.

You'd need to attach an OSS license for us to be able to using it here :)

**Comment by andrewabest** [comment]
Awesome to hear :) if you have any feedback on the functionality aside from adding new conventions, I'd welcome it. 

Is there any particular type of license you guys prefer? I'll look at adding an appropriate one that will also let existing users continue to use it without issue.

**Comment by brendankowitz** [comment]
Any of the non-restrictive license are ok, MIT, BSD, Apache, MS-PL

**Comment by andrewabest** [comment]
Sorry about the slow turnaround on this one @brendankowitz - I'll get it in along with the license this weekend.

**Comment by andrewabest** [comment]
I've added an MS-PL license to the repo as well @brendankowitz - thanks for the tip.

**Pull request merged**
