### PR TITLE
Ensure files matching pattern are included in project

### PR DESCRIPTION
**Pull request by Rophuine**
We have some people wanting to switch to WebStorm for web development, which won't talk to .csproj files - and we want to ensure files are still being included in the project for those still using VS.

I did some minor refactoring to share code between the existing Assembly conventions and the new Project convention, and added the test we needed. It accepts any pattern that Directory.GetFiles(...) can cope with.

I considered using the Assembly namespace, but it didn't quite seem to match.

### CODE REVIEW

**Comment by andrewabest** [comment]
Aside from fixing up the 4.5 project the PR looks good! I'm wondering if a ///<Summary> above the class might be good so people know the original intent of this convention - because it may not be obvious why you'd want to use it.

I'm pondering if a rename of IAssemblyConventionSpecification would be prudent - I'm going to crack open the code a little later and think about this one.

**Comment by Rophuine** [comment]
Further feedback from Clarky:
Should probably always ignore .csproj, .csproj.user, .orig maybe ...
Opt-out rather than opt-in wildcard would be useful.
Ignore bin/ and obj/ by default (other folders?)

Feedback from Jaime:
What about cross-platform paths? Consider .csproj which has '\' while the build system uses '/' directory separator char. @andrewabest what's your cross-platform compatibility policy for Conventional? Have you run into .csproj files with '/' instead of '\' in paths?

**Comment by andrewabest** [comment]
@Rophuine the feedback from Clarky seems specific to your convention, so it depends what is more applicable in your case. I'l prefer an opt in with an array of items to opt in, rather than an opt out. I'd prefer to be explicit about inclusions.

As far as paths using a different separator - I have yet to run into this - what specific instance would this occur in? My cross-platform policy is when I need it on a platform it doesn't work on, I'll adapt it then ;)

**Comment by andrewabest** [comment]
Just reviewing the additional convention specification type - the only difference at a glance seems to be that in the "Project" one, we derive and store the project file path and folder for access by derived classes, but aside from this the rest of it is identical?

I'm not entirely sure that the additional class and type of convention is justified here - I'd prefer just to add the additional properties to the existing base assembly convention specification type and build your convention on that.

Thoughts?

**Comment by Rophuine** [comment]
I'm happy to build on the existing one - I went with the project namespace because 'assembly' didn't seem right for the convention. It seems like the terms are interchangeable here anyway, so I'll switch it back to add the property to the existing base class and (I guess?) put both conventions in the existing namespace.

Sorry I've been slack on this - tennis. So much tennis to watch in January. It's bad for personal projects!

**Comment by Rophuine** [comment]
I probably still need to run this build into a real project and make sure it's doing what it should, but I've cleaned up the code and addressed most of the comments.

**Comment by andrewabest** [comment]
Looks good, I'll merge it in - if you find it needs a tweak for your needs feel free to PR it up again.

**Pull request merged**
